services:
  email-sender:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .env:/app/.env
      - maven-repo:/root/.m2

volumes:
  maven-repo: